### PR TITLE
Factor out metaproject admin gui into separate plugin

### PR DESCRIPTION
**Pull request by bdionne**

### CODE REVIEW

**Comment by bdionne** [comment]
This is basically removing all the admin GUI code, which will go into a separate plugin

**Comment by rgrinberg** [comment]
Do we need dependent PR's that will now depend on metaproject-admin as well as this?

**Comment by bdionne** [comment]
don't think so, which did you have in mind?

**Comment by rgrinberg** [comment]
Just a prophylactic check. Looks good.

**Pull request merged**
